<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <title>Document</title>
</head>
<body class="min-vh-100 d-flex flex-column">
<header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" data-savepage-href="/"
           href="https://php-page-analyzer-ru.hexlet.app/">Анализатор
            страниц</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" data-savepage-href="/"
                       href="https://php-page-analyzer-ru.hexlet.app/">Главная</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" data-savepage-href="/urls"
                       href="https://php-page-analyzer-ru.hexlet.app/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1></h1>
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO
                    пригодность</p>
                <form action="/urls" method="post" class="row" required="">
                    <div class="col-8">
                        <label for="text" class="visually-hidden">Url для
                            проверки</label>
                        <input type="text" name="url[name]" value=""
                               class="form-control form-control-lg"
                               placeholder="https://www.example.com">
                    </div>
                    <div class="col-2">
                        <input type="submit"
                               class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3"
                               value="Проверить">
                    </div>

                </form>

            </div>
        </div>
    </div>
</main>
<footer class="border-top py-3 mt-5 flex-shrink-0">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>